"use client";

import { useMemo, useState } from "react";
import { residualLabelsToCsv,residualOccurrencesToCsv,validPublicUrl,type DepartmentResidualLabelRow,type DepartmentResidualOccurrenceRow,type ResidualResolutionClass } from "./index";

const labels:Record<ResidualResolutionClass,string>={PERSON_EVIDENCE:"인물형 근거 있음",ORG_CURRENT:"현재 조직 확인",ORG_HISTORICAL:"과거 조직 확인",UNTYPED:"미분류 표기",AMBIGUOUS:"모호한 표기"};
const order:ResidualResolutionClass[]=["PERSON_EVIDENCE","ORG_CURRENT","ORG_HISTORICAL","UNTYPED","AMBIGUOUS"];
function download(name:string,body:string){const url=URL.createObjectURL(new Blob([body],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}

export function DepartmentResidualAnalysis({occurrences,summary}:{occurrences:DepartmentResidualOccurrenceRow[];summary:DepartmentResidualLabelRow[]}){
  const [filter,setFilter]=useState<ResidualResolutionClass|"ALL">("ALL");const [query,setQuery]=useState("");const [selected,setSelected]=useState<string|null>(null);
  const categories=useMemo(()=>new Map(order.map(key=>[key,{labels:summary.filter(x=>x.resolution_class===key).length,occurrences:summary.filter(x=>x.resolution_class===key).reduce((n,x)=>n+Number(x.residual_occurrence_count),0)}])),[summary]);
  const rows=useMemo(()=>summary.filter(row=>(filter==="ALL"||row.resolution_class===filter)&&(!query.trim()||row.raw_label.toLocaleLowerCase("ko-KR").includes(query.trim().toLocaleLowerCase("ko-KR")))).sort((a,b)=>Number(b.residual_occurrence_count)-Number(a.residual_occurrence_count)||a.normalized_label.localeCompare(b.normalized_label,"ko")),[summary,filter,query]);
  const detail=summary.find(row=>row.label_id===selected);const detailOccurrences=detail?occurrences.filter(row=>row.label_id===detail.label_id):[];
  return <section className="residual-analysis" aria-labelledby="residual-title">
    <div className="residual-title"><div><p className="eyebrow">관측 기반 분석</p><h2 id="residual-title">담당 표기 잔차</h2><p>사규예고의 담당 표기가 해당 release의 기준 조직명과 직접 일치하지 않은 관측 건입니다. 인물명, 과거 조직명, 기타 미분류 문자열이 포함됩니다.</p></div><dl><div><dt>잔차 관측</dt><dd>{occurrences.length.toLocaleString("ko-KR")}건</dd></div><div><dt>서로 다른 표기</dt><dd>{summary.length.toLocaleString("ko-KR")}개</dd></div></dl></div>
    <div className="residual-cards">{order.map(key=>{const value=categories.get(key)!;return <button key={key} className={filter===key?"active":""} onClick={()=>setFilter(filter===key?"ALL":key)}><span>{labels[key]}</span><strong>{value.labels.toLocaleString("ko-KR")}개</strong><small>{value.occurrences.toLocaleString("ko-KR")}건 관측</small></button>})}</div>
    <div className="residual-controls"><input aria-label="담당 표기 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="원문 표기 검색"/><select aria-label="잔차 상태" value={filter} onChange={e=>setFilter(e.target.value as ResidualResolutionClass|"ALL")}><option value="ALL">전체</option>{order.map(key=><option key={key} value={key}>{labels[key]}</option>)}</select><button onClick={()=>download("department-residual-occurrences.csv",residualOccurrencesToCsv(occurrences))}>잔차 관측 CSV</button><button onClick={()=>download("department-residual-labels.csv",residualLabelsToCsv(summary))}>표기 요약 CSV</button></div>
    <div className="table-scroll"><table className="regulations-table residual-table"><thead><tr><th>원문 표기</th><th>상태</th><th>관측 건수</th><th>최초 관측일</th><th>최근 관측일</th><th>관련 게시물</th></tr></thead><tbody>{rows.map(row=><tr key={row.label_id}><td><button className="department-link" onClick={()=>setSelected(selected===row.label_id?null:row.label_id)}>{row.raw_label||"미기재"}</button></td><td>{labels[row.resolution_class]}</td><td>{Number(row.residual_occurrence_count).toLocaleString("ko-KR")}</td><td>{row.first_seen_at??"미확인"}</td><td>{row.last_seen_at??"미확인"}</td><td>{Number(row.notice_count).toLocaleString("ko-KR")}</td></tr>)}</tbody></table></div>
    {detail&&<article className="residual-detail"><button className="residual-close" aria-label="상세 닫기" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">표기 상세</p><h3>{detail.raw_label||"미기재"}</h3><dl className="residual-meta"><div><dt>정규화 표기</dt><dd>{detail.normalized_label}</dd></div><div><dt>상태</dt><dd>{labels[detail.resolution_class]}</dd></div><div><dt>관측 범위</dt><dd>{detail.first_seen_at??"미확인"} ~ {detail.last_seen_at??"미확인"}</dd></div><div><dt>관측 / 게시물</dt><dd>{detail.residual_occurrence_count} / {detail.notice_count}</dd></div></dl>
      {detail.resolution_class==="PERSON_EVIDENCE"&&<section><h4>본문 관측 근거</h4><p>담당 표기와 동일한 문자열이 문서 본문에서 인물형 문맥으로도 관측된 경우입니다. 실제 인물 신원, 역할 또는 소속을 확정한 결과가 아닙니다.</p><p>mention 관측 {Number(detail.mention_occurrence_count).toLocaleString("ko-KR")}건</p><ul>{Object.entries(detail.extractor_rule_distribution).map(([rule,count])=><li key={rule}><code>{rule}</code><span>{count}건</span></li>)}</ul><div className="evidence-links">{detail.mention_source_locations.filter(validPublicUrl).map(url=><a key={url} href={url} target="_blank" rel="noopener noreferrer">본문 근거 원문 ↗</a>)}</div></section>}
      {(detail.resolution_class==="ORG_CURRENT"||detail.resolution_class==="ORG_HISTORICAL")&&<section><h4>조직 판정</h4><p><b>{detail.org_official_name}</b> · {detail.resolution_class==="ORG_CURRENT"?"현재 공식 조직자료에서 확인":"관측 시점의 공식·보존 근거에서 확인"}</p><p>유효기간: {detail.org_valid_from??"시작일 미확인"} ~ {detail.org_valid_to??"종료일 미확인"}</p>{validPublicUrl(detail.official_evidence_url)&&<a href={detail.official_evidence_url!} target="_blank" rel="noopener noreferrer">공식 조직 근거 보기 ↗</a>}{detail.lineage_edges.map((edge,index)=><div className="lineage-text" key={`${edge.relation_type}-${edge.effective_date}-${index}`}><b>{edge.from_name}</b><span> — {edge.edge_scope} 이관 → </span><b>{edge.to_name}</b><small>{edge.effective_date}</small>{validPublicUrl(edge.evidence_url)&&<a href={edge.evidence_url} target="_blank" rel="noopener noreferrer">근거 ↗</a>}</div>)}{detail.lineage_edges.length>0&&<p className="lineage-warning">이 관계는 확인된 특정 기능의 이관이며 조직 전체의 명칭변경·승계를 뜻하지 않습니다.</p>}</section>}
      <section><h4>근거 게시물</h4><ul className="residual-notices">{detailOccurrences.map(item=><li key={item.residual_id}><span>{item.posted_at}</span>{validPublicUrl(item.source_location)?<a href={item.source_location} target="_blank" rel="noopener noreferrer">{item.title}</a>:<b>{item.title}</b>}<small>{item.raw_label}</small></li>)}</ul></section>
    </article>}
  </section>;
}
